name: Build App

on:
  push:
    tags:
      - 'v[0-9]+.*'
      
permissions:
  contents: read
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/keithlinneman/build-system@sha256:73b47db5685a0c18a4e77e6a33dc84c43a936e84facace5bada8b97bd1106cd4
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Configure git safe directory
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::148142827637:role/app-linnemanlabs-web-build
          aws-region: us-east-2

      - name: Build and release
        run: |
          /build-system/build.sh \
            --repo . \
            --ref ${{ github.sha }} \
            --track stable
